apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels: 
    name: myapp
spec:
  containers:
  - name: myapp
    image: myapp
    imagePullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  restartPolicy: Never

